### ISSUE TITLE
ValueError: Unknown storage engine

### ISSUE THREAD

**Issue by alpha-alexxx** [odysseusmax/utube#33]
Has somebody solved this error before?

File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ankitinter9/bot/__main__.py", line 13, in <module>
    UtubeBot().run()
  File "/home/ankitinter9/bot/utubebot.py", line 8, in __init__
    super().__init__(
  File "/home/ankitinter9/venv/lib/python3.10/site-packages/pyrogram/client.py", line 243, in __init__
    raise ValueError("Unknown storage engine")
ValueError: Unknown storage engine
(venv) 12:27 ~ $ SESSION_NAME=lethargic_Charge
(venv) 12:27 ~ $ python -m bot
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ankitinter9/bot/__main__.py", line 13, in <module>
    UtubeBot().run()
  File "/home/ankitinter9/bot/utubebot.py", line 8, in __init__
    super().__init__(
  File "/home/ankitinter9/venv/lib/python3.10/site-packages/pyrogram/client.py", line 243, in __init__
    raise ValueError("Unknown storage engine")
ValueError: Unknown storage engine

**Comment by Araci-co** [comment]
I have same problem
```
root@wud73vp9:~/utube# python3 -m bot
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/utube/bot/__main__.py", line 13, in <module>
    UtubeBot().run()
  File "/root/utube/bot/utubebot.py", line 8, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 243, in __init__
    raise ValueError("Unknown storage engine")
ValueError: Unknown storage engine
```

**Comment by vpcreatz** [comment]
Use
bash python3 -m bot
To run. If problem not resolved install requirements.txt file and fork this repo with different name and type forked repo url and run.
