### ISSUE TITLE
error pyrogram

### ISSUE THREAD

**Issue by MRJ-Badshah** [odysseusmax/utube#37]
`Traceback (most recent call last):
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/utube/bot/__main__.py", line 13, in <module>
    UtubeBot().run()
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/client.py", line 637, in load_session
    await Auth(
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 274, in create
    raise e
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 89, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 67, in invoke
    return self.unpack(response)
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 60, in unpack
    return TLObject.read(b)
  File "/home/runner/utube/.pythonlibs/lib/python3.10/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 0`

**Comment by Alihtt** [comment]
According to the [owner response](https://github.com/pyrogram/pyrogram/issues/1249#issuecomment-1501055946) in GitHub, the main reason of this issue is caused by server or network issue, not from the code or module itself.

**Comment by git-preet** [comment]
This error typically occurs when the code tries to access a dictionary or a similar data structure using a key that does not exist.
